import mongoose from "../db/connection";

 const Food = new mongoose.Schema({
    index: Number,
    NDB_No: Number,
    Shrt_Desc: String,
    Water_g: Number,
    Energ_Kcal: Number,
    Protein_g: Number,
    Lipid_Tot_g: Number,
    Ash_g: Number,
    Carbohydrt_g: Number,
    Fiber_TD_g: Number,
    Sugar_Tot_g: Number,
    Calcium_mg: Number,
    Iron_mg: Number,
    Magnesium_mg: Number,
    Phosphorus_mg: Number,
    Potassium_mg: Number,
    Sodium_mg: Number,
    Zinc_mg: Number,
    Copper_mg: Number,
    Manganese_mg: Number,
    Selenium_µg: Number,
    Vit_C_mg: Number,
    Thiamin_mg: Number,
    Riboflavin_mg: Number,
    Niacin_mg: Number,
    Panto_Acid_mg: Number,
    Vit_B6_mg: Number,
    Folate_Tot_µg: Number,
    Folic_Acid_µg: Number,
    Food_Folate_µg: Number,
    Folate_DFE_µg: Number,
    Choline_Tot_mg: Number,
    Vit_B12_µg: Number,
    Vit_A_IU: Number,
    Vit_A_RAE: Number,
    Retinol_µg: Number,
    Alpha_Carot_µg: Number,
    Beta_Carot_µg: Number,
    Beta_Crypt_µg: Number,
    Lycopene_µg: Number,
    LutZea_µg: Number,
    Vit_E_mg: Number,
    Vit_D_µg: Number,
    Vit_D_IU: Number,
    Vit_K_µg: Number,
    FA_Sat_g: Number,
    FA_Mono_g: Number,
    FA_Poly_g: Number,
    Cholestrl_mg: Number,
    GmWt_1: Number,
    GmWt_Desc1: String,
    GmWt_2: Number,
    GmWt_Desc2: String,
    Refuse_Pct: Number
 })

 export default mongoose.model("Food", Food)